export const burgers = [
  {id: "burger-donald", name: "The Hamberder", desc: "Great american food", price: "49.9k"},
  {id: "burger-beaconcheese", name: "Beacon Cheeseburger", desc: "16oz beef patty, bacon, cheese", price: "54.9k"},
  {id: "burger-canada", name: "Hot Hamburg Sandwich", desc: "The Hamberder, gravy, topped with cheese", price: "54.9k"},
  {id: "burger-barbados", name: "Broasted Sizzler", desc: "Deep-fried chicken, lettuce, tomato, onion", price: "49.9k"},
  {id: "burger-mexican", name: "Hamburguesas Mexicanas", desc: "Beef patty, bacon, cheese, avocado, jalapeño", price: "49.9k"},
  {id: "burger-chile", name: "Chilean Italiano", desc: "Churrasco, tomatoes, mashed avocado, mayo", price: "49.9k"},
  {id: "burger-uruguay", name: "Chivito", desc: "Churrasco, mozzarella, tomatoes, olives, mayo", price: "49.9k"},
  {id: "burger-uk", name: "Codfather", desc: "Beer-battered cod, tartar sauce", price: "54.9k"},
  {id: "burger-german", name: "Hamburg Steak", desc: "Chopped beef, no bun", price: "54.9k"},
  {id: "burger-danish", name: "Bøfsandwich", desc: "Beef patty, french mustard, onions 3-ways", price: "54.9k"},
  {id: "burger-finland", name: "Poroburger", desc: "Reindeer patty, cheese, lingonberry jam", price: "59.9k"},
  {id: "burger-turkey", name: "Salt Bae", desc: "16oz wagyu beef, cheese, salt", price: "59.9k"},
  {id: "burger-india", name: "Vada Pav", desc: "Deep fried potato, spicy chutney, chillies, onion", price: "39.9k"},
  {id: "burger-pakistan", name: "Bun Kebab", desc: "Beef patty, green chutney, grilled onions, tomatoes", price: "39.9k"},
  {id: "burger-malaysia", name: "Ramly Burger", desc: "Beef patty wrapped in fried egg", price: "39.9k"},
  {id: "burger-japan", name: "Teriyaki", desc: "Chicken, teriyaki sauce,lettuce, tomatoes", price: "59.9k"},
  {id: "burger-australia", name: "Aussie Special", desc: "Organic crumbled mushroom, gruyere, lettuce, tomatoes, aioli", price: "54.9k"},
  {id: "burger-nz", name: "Kiwi Burger", desc: "Beef patty, beetroot, fried egg, bacon", price: "54.9k"},
]

export const sides = [
  {id: "sides-fries", name: "French Fries", desc: "Thick or thin", price: "19.9k"},
  {id: "sides-canada", name: "Poutine", desc: "Canadian fries, gravy, cheese", price: "22.9k"},
  {id: "sides-us", name: "Mac n Cheese", desc: "Maccaroni, béchamel sauce, gruyere, cheddar, emmental", price: "24.9k"},
  {id: "sides-uk", name: "Mushy Peas", desc: "Peas mushed, mint", price: "19.9k"},
  {id: "sides-uk", name: "Dressed Fries", desc: "Thick fries, cheese sauce, chilli beef", price: "22.9k"},
  {id: "sides-spain", name: "Patatas Bravas", desc: "Deep-fried potato cubes, spicy tomato sauce", price: "20.9k"},
  {id: "sides-med", name: "Hummus + Pita", desc: "Mashed chickpeas, tahini, olive oil, lemon", price: "21.9k"},
  {id: "sides-sa", name: "Spicy Rice", desc: "Long-grain rice, onion, peppers, Nandos spice blend", price: "21.9k"},
  {id: "sides-japan", name: "Chizza", desc: "Deep-fried chicken pizza", price: "25.9k"},
  {id: "sides-pinoy", name: "Jolly Spaghetti", desc: "Spaghetti, sweet tomato sauce", price: "20.9k"},
  {id: "sides-pinoydouble", name: "Double Down", desc: "Sausage wrapped in deep-fried chicken", price: "21.9k"},
  {id: "sides-malaysia", name: "Kaya Toast", desc: "Kaya jam, butter", price: "20.9k"},
  {id: "sides-japan", name: "Okazu", desc: "Gohan, misoshiru, umeboshi, tsukemono, natto", price: "25.9k"},
  {id: "sides-korea", name: "Banchan", desc: "Bap, gamja-tang, kimchi, namul, bokkeum, danmuji", price: "26.9k"},
]

export const drinks = [
  {id: "drinks-soda", name: "Soda Fountain", desc: "Free flow soda", price: "19.9k"},
  {id: "drinks-guinness", name: "Guinness", desc: "Irish dry stout", price: "33.9k"},
  {id: "drinks-ipa", name: "IPA", desc: "Hoppy, bitter, juicy", price: "34.9k"},
  {id: "drinks-pilsner", name: "Pilsner Urquell", desc: "Golden, nice body, good head", price: "33.9k"},
  {id: "drinks-kirin", name: "Kirin Ichiban", desc: "First press, crisp, refreshing", price: "34.9k"},
  {id: "drinks-spain", name: "Sangria", desc: "Garnacha, sweet citrus fruits, chilled", price: "33.9k"},
  {id: "drinks-spain", name: "Campari Spritz", desc: "Campari, prosecco, soda water", price: "36.9k"},
  {id: "drinks-peru", name: "Pisco Sour", desc: "Pisco, egg white, bitters, lime juice", price: "36.9k"},
  {id: "drinks-peru", name: "Caipirinha", desc: "Cachaça, syrup, fresh lime", price: "36.9k"},
  {id: "drinks-japan", name: "Sake", desc: "Aged rice wine, served hot or cold", price: "38.9k"},
  {id: "drinks-korea", name: "Poktanju", desc: "Beer, soju", price: "33.9k"},
]

export const dessert = [
  {id: "dessert-us", name: "Apple Pie", desc: "Flaky crust, pink lady, whipped cream, vanilla ice-cream", price: "33.9k"},
  {id: "dessert-peru", name: "Picarones", desc: "Sweet potato & squash dougnut, anise seed, chancaca syrup", price: "29.9k"},
  {id: "dessert-argentina", name: "Pastelitos", desc: "Flaky puff pastry, sweet potato filling, syrup", price: "29.9k"},
  {id: "dessert-uk", name: "Banoffee Pie", desc: "Digestives crust, bananas, toffee, whipped cream", price: "35.9k"},
  {id: "dessert-france", name: "Macaron", desc: "Almond meringue cookie, ganache", price: "35.9k"},
  {id: "dessert-cremebrulee", name: "Crème Brulée", desc: "Creamy custard, browned caramel", price: "33.9k"},
  {id: "dessert-belgium", name: "Belgian Waffles", desc: "Warm waffles, nutella, powdered sugar", price: "34.9k"},
  {id: "dessert-italy", name: "Gelato", desc: "Raspberry, pistachio, rum, chocolate", price: "29.9k"},
  {id: "dessert-turkey", name: "Baklava", desc: "Phyllo pastry, honey, pistachio, walnut, hazelnut, ", price: "37.9k"},
  {id: "dessert-sa", name: "Koeksisters", desc: "Deep-fried dough rolls, cold sugar syrup", price: "29.9k"},
  {id: "dessert-japan", name: "Mochi", desc: "Glutinous rice ball, sweet filling", price: "39.9k"},
  {id: "dessert-aus", name: "Lamingtons", desc: "Sponge cake, chocolate coating, coconut sprinkles", price: "32.9k"},
]